menus/urls.py
from django.conf.urls import url


from .views import (
    ItemListView,
    ItemDetailView,
    ItemCreateView,
    ItemUpdateView,
    )

urlpatterns = [
    url(r'^$', ItemListView.as_view(), name='list'),
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    # url(r'^(?P<pk>\d+)/update/$', ItemUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'), #pk default
]

trydjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, PasswordResetView, LogoutView

from basics.views import AboutView, AboutTemplateView

from profiles.views import ProfileFollowToggle, RegisterCreateView, activate_user_view

from menus.views import HomeView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^password_reset/$', PasswordResetView.as_view(), name='password_reset'),
    url(r'^register/$', RegisterCreateView.as_view(), name='register'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),


    url(r'^other/$', TemplateView.as_view(template_name='other.html'), name='other'),
    url(r'^about/(?P<id>\d+)/$', AboutTemplateView.as_view(), name='about'),


    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),

    url(r'^items/', include('menus.urls', namespace='menus')),

    url(r'^profiles/', include('profiles.urls', namespace='profiles')),

    url(r'^follow/$', ProfileFollowToggle.as_view(), name='follow'),
]

templates/snippets/css.html
<!-- Bootstrap core CSS -->
<link href="https://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="https://v4-alpha.getbootstrap.com/examples/starter-template/starter-template.css" rel="stylesheet">

templates/snippets/form.html
{% if form.errors.non_field_errors %}
   {{ form.errors.non_field_errors }}
{% endif %}
</p>
<form method="POST"> 
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">SAVE</button>
</form>

templates/snippets/js.html
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
<script src="https://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>

templates/snippets/nav.html
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Navbar</a>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/">about</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'other' %}">Other</a>
      </li>
      {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Restaurants</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="{% url 'restaurants:list' %}">List</a>
            <a class="dropdown-item" href="{% url 'restaurants:create' %}">Create</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menus</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="{% url 'menus:list' %}">List</a>
            <a class="dropdown-item" href="{% url 'menus:create' %}">Create</a>
          </div>
        </li>      
      {% endif %}

    </ul>
    <form type="GET" action="." class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" name="q" value="{{request.GET.q}}" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      <a class="nav-link" href="{% url 'login' %}">Login</a>
    </form>
  </div>
</nav>