menus/urls.py
from django.conf.urls import url


from .views import (
    ItemListView,
    ItemDetailView,
    ItemCreateView,
    ItemUpdateView,
    )

urlpatterns = [
    url(r'^$', ItemListView.as_view(), name='list'),
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    # url(r'^(?P<pk>\d+)/update/$', ItemUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'), #pk default
]

trydjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, PasswordResetView, LogoutView

from basics.views import AboutView, AboutTemplateView

from profiles.views import ProfileFollowToggle, RegisterCreateView, activate_user_view

from menus.views import HomeView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^password_reset/$', PasswordResetView.as_view(), name='password_reset'),
    url(r'^register/$', RegisterCreateView.as_view(), name='register'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),


    url(r'^other/$', TemplateView.as_view(template_name='other.html'), name='other'),
    url(r'^about/(?P<id>\d+)/$', AboutTemplateView.as_view(), name='about'),


    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),

    url(r'^items/', include('menus.urls', namespace='menus')),

    url(r'^profiles/', include('profiles.urls', namespace='profiles')),

    url(r'^follow/$', ProfileFollowToggle.as_view(), name='follow'),
]

menus/models.py
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse

from restaurants.models import RestaurantLocation

# Create your models here.
class Item(models.Model):
	#associations
	user 		= models.ForeignKey(settings.AUTH_USER_MODEL)
	restaurant 	= models.ForeignKey(RestaurantLocation)

	#items
	name 		= models.CharField(max_length=120)
	contents 	= models.TextField(help_text='separate each item by comma')
	excludes 	= models.TextField(blank=True, null=True, help_text='separate each item by comma')
	public 		= models.BooleanField(default=True)
	timestamp	= models.DateTimeField(auto_now_add=True)
	updated		= models.DateTimeField(auto_now=True)


	def __str__(self):
		return self.name
		
	def get_absolute_url(self):
		return reverse('menus:detail', kwargs={'pk': self.pk})

	class Meta:
		ordering = ['-updated', '-timestamp'] #Item.objects.all() gives the newest first


	def get_contents(self):
		return self.contents.split(",")

	def get_excludes(self):
		return self.excludes.split(",")	

menus/forms.py
from django import forms

from restaurants.models import RestaurantLocation

from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
    	model = Item
    	fields = [
    		'restaurant',
    		'name',
    		'contents',
    		'excludes',
    		'public',
    	]

    def __init__(self, user=None, *args, **kwargs):
    	print(user)
    	super(ItemForm, self).__init__(*args,**kwargs)
    	self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner=user).exclude(item__isnull=True)

menus/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, View
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
from .forms import ItemForm
from .models import Item


class HomeView(View):

	def get(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return render(request, "home.html", {})

		user = request.user
		is_following_user_ids = [x.user.id for x in user.is_following.all()]
		qs = Item.objects.filter(user__id__in=is_following_user_ids, public=True).order_by("-updated")[:3]

		return render(request, "menus/home.html", {'object_list': qs})

class ItemListView(LoginRequiredMixin, ListView):
	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)

class ItemDetailView(LoginRequiredMixin, DetailView):
	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)

class ItemCreateView(LoginRequiredMixin, CreateView):
	template_name = 'form.html'
	form_class = ItemForm
	def form_valid(self, form):
		instance = form.save(commit=False)
		instance.user = self.request.user
		return super(ItemCreateView, self).form_valid(form)

	def get_form_kwargs(self):
		kwargs = super(ItemCreateView, self).get_form_kwargs()
		kwargs['user'] = self.request.user
		# kwargs['instance'] = Item.objects.filter(user=self.request.user).first()
		return kwargs

	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)

	def get_context_data(self, *args, **kwargs):
		context = super(ItemCreateView, self).get_context_data(*args, **kwargs)
		context['title'] = 'Add Item'
		return context

class ItemUpdateView(LoginRequiredMixin, UpdateView):
	template_name = 'menus/detail-update.html'
	form_class = ItemForm

	def form_valid(self, form):
		instance = form.save(commit=False)
		instance.user = self.request.user
		return super(ItemUpdateView, self).form_valid(form)

	def get_queryset(self):
		return Item.objects.filter(user=self.request.user)		

	def get_context_data(self, *args, **kwargs):
		context = super(ItemUpdateView, self).get_context_data(*args, **kwargs)
		context['title'] = 'Update Item'
		return context

	def get_form_kwargs(self):
		kwargs = super(ItemUpdateView, self).get_form_kwargs()
		kwargs['user'] = self.request.user
		# kwargs['instance'] = Item.objects.filter(user=self.request.user).first()
		return kwargs

menus/templates/menus/detail-update.html
{% extends "base.html" %}
{% block head_title %} Menu Items || {{ block.super}} {% endblock head_title %}

{% block content %}
<div class="starter-template">
  <h1>Menu Items </h1>
  <p class="lead">
  	<ul>
	  	<a href="{{ form.instance.get_absolute_url }}"> <h2> {{form.instance.name}} </h2></a><br/>

	  	<p>Location: {{ form.instance.restaurant.name }}</p>
{# 	  	<a href="/restaurants/{{form.instance.slug}}"> <h2> {{form.instance.name}} </h2></a> #}
		{% if form.instance.contents %}
		    
		
		
		<h3>Contents</h3>
		<ul>
			{% for item in form.instance.get_contents %}
				<li>{{ item }}</li>
			{% endfor %}
		</ul>
		{% endif %}
		{% if form.instance.excludes %}
		<h3>Excludes</h3>
		<ul>
			{% for item in form.instance.get_excludes %}
				<li>{{ item }}</li>
			{% endfor %}
		</ul>		
		{% endif %}
	</ul>  
  </p>
</div>
<h3>Make changes</h3>
{% include 'snippets/form.html' with form=form %}
{% endblock content %}

menus/templates/menus/home.html
{% extends "base.html" %}
{% block head_title %} Following || {{ block.super}} {% endblock head_title %}

{% block content %}
<div class="starter-template">
	  {% for obj in object_list %}
	  	<div class="jumbotron jumbotron-fluid">
			<div class="container">
				<h1 class="display-3">{{ obj.name }}</h1>
				<a href="{% url 'profiles:detail' username=obj.user.username %}">
					<h2 class="display-5">{{ obj.user.username }} </h2>
				</a>
				<a href="{% url 'profiles:detail' username=obj.user.username %}?q={{obj.restaurant.location}}">
				<h7 class="display-7">{{ obj.restaurant.location }}
				</a>	
				 | 
				<a href="{% url 'profiles:detail' username=obj.user.username %}?q={{obj.restaurant.category}}">
				 {{ obj.restaurant.category }}</h7>
				</a><br/>
		  		<ul class="list-group">			
	  				{% for ing in item.get_contents %}
	  					<li class="list-group-item list-group-item-success">
	  						<a href="{% url 'profiles:detail' username=obj.user.username %}?q={{ ing }}">{{ ing }}</a>
	  					</li>
	  				{% endfor %}	
	  				{% for ing in item.get_excludes %}
	  					<li class="list-group-item list-group-item-danger">
	  						{{ ing }}
	  					</li>
	  				{% endfor %}
		  		</ul>
			</div>
		</div>
	  {% endfor %}
</div>

{% endblock content %}



  
  <p class="lead">
  	<ul>

	</ul>  
  </p>

menus/templates/menus/item_detail.html
{% extends "base.html" %}
{% block head_title %} Menu Items || {{ block.super}} {% endblock head_title %}

{% block content %}
<div class="starter-template">
  <h1>Menu Items </h1>
  <p class="lead">
  	<ul>
	  	<a href="{{ object.get_absolute_url }}"> <h2> {{object.name}} </h2></a><br/>

	  	<p>Location: {{ object.restaurant.name }}</p>
{# 	  	<a href="/restaurants/{{object.slug}}"> <h2> {{object.name}} </h2></a> #}
		{% if object.contents %}
		    
		
		
		<h3>Contents</h3>
		<ul>
			{% for item in object.get_contents %}
				<li>{{ item }}</li>
			{% endfor %}
		</ul>
		{% endif %}
		{% if object.excludes %}
		<h3>Excludes</h3>
		<ul>
			{% for item in object.get_excludes %}
				<li>{{ item }}</li>
			{% endfor %}
		</ul>		
		{% endif %}
	</ul>  
  </p>
</div>

{% endblock content %}

menus/templates/menus/item_list.html
{% extends "base.html" %}
{% block head_title %} Menu Items || {{ block.super}} {% endblock head_title %}

{% block content %}
<div class="starter-template">
  <h1>Menu Items </h1>
  <p class="lead">
  	<ul>
	  {% for obj in object_list %}
	  	<a href="{{ obj.get_absolute_url }}"> <h2> {{obj.name}} </h2></a><br/>
{# 	  	<a href="/restaurants/{{obj.slug}}"> <h2> {{obj.name}} </h2></a> #}
		{% if obj.contents %}
		    
		
		
		<h3>Contents</h3>
		<ul>
			{% for item in obj.get_contents %}
				<li>{{ item }}</li>
			{% endfor %}
		</ul>
		{% endif %}
		{% if obj.excludes %}
		<h3>Excludes</h3>
		<ul>
			{% for item in obj.get_excludes %}
				<li>{{ item }}</li>
			{% endfor %}
		</ul>		
		{% endif %}
	  {% endfor %}
	</ul>  
  </p>
</div>

{% endblock content %}